name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]
          node: [18]

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build
        env:
          NITRO_PRESET: cloudflare

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}