name: Deploy to Deno

on:
  workflow_dispatch:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          NITRO_PRESET: deno

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: peakville
          entrypoint: server/index.ts
          root: .output